os: linux
language: node_js
node_js:
- '10'
- '11'
- '12'
cache: yarn
script: yarn ci
jobs:
  include:
    - stage: deploy
      if: tag IS present
      node_js: '12'
      script: yarn build
      before_deploy:
      - cd dist
      deploy:
        provider: npm
        tag: travis
        skip_cleanup: true
        email: "ijpiantanida@gmail.com"
        api_key: $NPM_TOKEN
        on:
          tags: true
